### ISSUE TITLE
Setting ROS_Master_URI in Battery Monitor

### ISSUE THREAD

**Issue by Jabro** [a2s-institute/youbot_diagnostics#1]
Hello,

is there any particular reason for setting the ros_master_uri in the youbot_battery_monitor.sh file, which should be called by the udev rule?

Best Regards,
Jabro

**Comment by frederikhegger** [comment]
Yes, because "ros::master::check()" access the environment variable in order to check whether a roscore is already running under this URL. If you do not specify it, you will receive an error message.

**Comment by Jabro** [comment]
Ok but if you set the ROS_MASTER_URI environment variable on the forehand,  to let the ros master run on a different system, your ROS master is overridden. Wouldn't it be better to check whether it is set and only set it to localhost when it isn't? 

-----Original Message-----

**Comment by frederikhegger** [comment]
yes, definitively. Have you done it already? If yes, could you send us a pull request, pelase.

**Comment by Jabro** [comment]
Hi,

 I haven't done it so far. Didn't have to time to test this package so far. Just noticed that it wasn't running out of the box and peaked in the file and then in turn noticed that setting the ROS_MASTER_URI can cause misconfiguration and is not expected by the user.

**Comment by frederikhegger** [comment]
Addressed by 3b07e51b3a9bff132fedbdd0cb1c6af0ad05531c
